import { of } from 'rxjs';

export class MockStorageMap {
  get(_key: string) { return of(null); }
  set(_key: string, _val: any) { return of(undefined); }
}

export function createMockApiService(overrides?: any): any {
  return Object.assign({
    settings: {
      id: 1,
      language: 'en',
      tmdb_configuration: { images: { secure_base_url: 'https://image.tmdb.org/t/p/' } },
      tmdb_languages: ['en'],
      jackett_token: 'real-token',
      jackett_default_token: 'default',
      jackett_host: 'jackett',
      jackett_port: 9117,
      transmission_host: 'transmission',
      transmission_port: 9091,
      transmission_tv_download_dir: '/tv',
      transmission_movie_download_dir: '/movies',
      websocket_url: 'ws://localhost:8000/ws',
      preferred_media_category: 'movie',
      is_debug: true,
    },
    user: { id: 1, username: 'admin', is_staff: true },
    userToken: 'test-token',
    users: [],
    qualities: [],
    qualityProfiles: [],
    mediaCategories: [],
    watchTVShows: [],
    watchTVSeasons: [],
    watchTVSeasonRequests: [],
    watchTVEpisodes: [],
    watchMovies: [],
    mediaUpdated$: of(true),
    isLoggedIn: () => true,
    userIsStaff: () => true,
    fetchSettings: () => of([]),
    fetchUser: () => of([]),
    fetchCoreData: () => of(null),
    fetchWatchMedia: () => of([]),
    fetchQualities: () => of([]),
    fetchQualityProfiles: () => of([]),
    fetchMediaCategories: () => of({ mediaCategories: [] }),
    fetchWatchTVShows: () => of([]),
    fetchWatchTVSeasons: () => of([]),
    fetchWatchTVEpisodes: () => of([]),
    fetchWatchTVSeasonRequests: () => of([]),
    fetchWatchMovies: () => of([]),
    fetchUsers: () => of([]),
    searchMedia: () => of([]),
    searchMediaDetail: () => of({}),
    searchSimilarMedia: () => of([]),
    searchRecommendedMedia: () => of([]),
    searchTorrents: () => of([]),
    fetchMovieGenres: () => of({ genres: [] }),
    fetchTVGenres: () => of({ genres: [] }),
    fetchCurrentTorrents: () => of([]),
    fetchMediaVideos: () => of({ results: [] }),
    fetchGitCommit: () => of({ commit: 'abc123' }),
    verifyJackettIndexers: () => of([]),
    verifySettings: () => of({ success: true }),
    login: () => of({ token: 'abc' }),
    updateSettings: () => of({}),
    updateQualityProfile: () => of({}),
    deleteQualityProfile: () => of({}),
    createQualityProfile: () => of({}),
    watchTVShow: () => of({}),
    watchTVEpisode: () => of({}),
    watchTVSeasonRequest: () => of({}),
    watchMovie: () => of({}),
    unWatchTVShow: () => of({}),
    unWatchTVEpisode: () => of({}),
    unWatchTVSeason: () => of({}),
    unWatchMovie: () => of({}),
    updateWatchTVShow: () => of({}),
    updateUser: () => of({}),
    createUser: () => of({}),
    deleteUser: () => of({}),
    download: () => of({ success: true }),
    importMedia: () => of({}),
    queueTask: () => of({}),
    sendNotification: () => of({}),
    deleteAllBlacklists: () => of({}),
    discoverMovies: () => of({}),
    discoverTV: () => of({}),
    discoverRottenTomatoesMedia: () => of({}),
    openSubtitlesAuth: () => of({}),
    blacklistRetryMovie: () => of({}),
    blacklistRetryTVSeason: () => of({}),
    blacklistRetryTVEpisode: () => of({}),
  }, overrides || {});
}

