# accept an image tag build argument to define a "copy_app_image" FROM image to copy the prebuilt app from
ARG tag=latest
FROM lardbit/nefarious:${tag} as copy_app_image

# base image
FROM resin/armv7hf-ubuntu

WORKDIR /app

# copy pre-built app from "copy_app_image" image
COPY --from=copy_app_image /app .

RUN ["cross-build-start"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3 \
    python3-dev \
    python3-venv \
    python3-gdbm \
    && python3 -m venv /env \
    && /env/bin/pip install --no-cache-dir -r requirements.txt \
    && apt-get remove -y \
        build-essential \
        python3-venv \
        python3-dev \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* \
    && true

RUN ["cross-build-end"]

EXPOSE 80

ENTRYPOINT ["/app/docker-entrypoint.sh"]
