# Generated by Django 2.1.1 on 2018-11-03 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NefariousSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jackett_host', models.CharField(default='localhost', max_length=500)),
                ('jackett_port', models.IntegerField(default=9117)),
                ('jackett_token', models.CharField(max_length=500)),
                ('transmission_host', models.CharField(max_length=500)),
                ('transmission_port', models.IntegerField(default=9091)),
                ('transmission_user', models.CharField(max_length=500)),
                ('transmission_pass', models.CharField(max_length=500)),
                ('transmission_download_dir', models.CharField(max_length=500)),
                ('tmdb_token', models.CharField(max_length=500)),
                ('tmdb_configuration', jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True)),
                ('tmdb_configuration_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_movie_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('poster_image_url', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('collected', models.BooleanField(default=False)),
                ('collected_date', models.DateTimeField(blank=True, null=True)),
                ('transmission_torrent_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_immediately_watch_movie', 'Can immediately start watching movies'),),
            },
        ),
        migrations.CreateModel(
            name='WatchTVEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_episode_id', models.IntegerField(unique=True)),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('collected', models.BooleanField(default=False)),
                ('collected_date', models.DateTimeField(blank=True, null=True)),
                ('transmission_torrent_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchTVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_show_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('poster_image_url', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_immediately_watch_tv', 'Can immediately start watching tv shows'),),
            },
        ),
        migrations.AddField(
            model_name='watchtvepisode',
            name='watch_tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nefarious.WatchTVShow'),
        ),
        migrations.AlterUniqueTogether(
            name='watchtvepisode',
            unique_together={('watch_tv_show', 'season_number', 'episode_number')},
        ),
    ]
