# Generated by Django 2.1.1 on 2018-11-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nefarioussettings',
            name='transmission_download_dir',
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='transmission_movie_download_dir',
            field=models.CharField(default='movies', help_text='Relative to download path', max_length=500),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='transmission_tv_download_dir',
            field=models.CharField(default='tv', help_text='Relative to download path', max_length=500),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='tmdb_configuration_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
