# Generated by Django 2.1.1 on 2018-11-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0002_auto_20181110_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='transmission_movie_download_dir',
            field=models.CharField(default='movies/', help_text='Relative to download path', max_length=500),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='transmission_tv_download_dir',
            field=models.CharField(default='tv/', help_text='Relative to download path', max_length=500),
        ),
    ]
