# Generated by Django 2.1.1 on 2018-12-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0006_auto_20181203_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmovie',
            name='transmission_torrent_hash',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchtvepisode',
            name='transmission_torrent_hash',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
