# Generated by Django 2.1.1 on 2018-12-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0008_auto_20181203_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='quality_profile',
            field=models.CharField(choices=[('any', 'any'), ('sd', 'sd'), ('hd-720p', 'hd-720p'), ('hd-720p-1080p', 'hd-720p-1080p'), ('hd-1080p', 'hd-1080p'), ('ultra-hd', 'ultra-hd')], default='hd-720p-1080p', max_length=500),
        ),
        migrations.AlterField(
            model_name='watchmovie',
            name='quality_profile_custom',
            field=models.CharField(blank=True, choices=[('any', 'any'), ('sd', 'sd'), ('hd-720p', 'hd-720p'), ('hd-720p-1080p', 'hd-720p-1080p'), ('hd-1080p', 'hd-1080p'), ('ultra-hd', 'ultra-hd')], max_length=500),
        ),
        migrations.AlterField(
            model_name='watchmovie',
            name='transmission_torrent_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watchtvepisode',
            name='quality_profile_custom',
            field=models.CharField(blank=True, choices=[('any', 'any'), ('sd', 'sd'), ('hd-720p', 'hd-720p'), ('hd-720p-1080p', 'hd-720p-1080p'), ('hd-1080p', 'hd-1080p'), ('ultra-hd', 'ultra-hd')], max_length=500),
        ),
        migrations.AlterField(
            model_name='watchtvepisode',
            name='transmission_torrent_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watchtvshow',
            name='quality_profile_custom',
            field=models.CharField(blank=True, choices=[('any', 'any'), ('sd', 'sd'), ('hd-720p', 'hd-720p'), ('hd-720p-1080p', 'hd-720p-1080p'), ('hd-1080p', 'hd-1080p'), ('ultra-hd', 'ultra-hd')], max_length=500),
        ),
    ]
