# Generated by Django 2.1.1 on 2018-12-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0010_auto_20181208_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchmovie',
            name='transmission_torrent_id',
        ),
    ]
