# Generated by Django 2.1.1 on 2018-12-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0011_remove_watchmovie_transmission_torrent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchtvepisode',
            name='transmission_torrent_id',
        ),
    ]
