# Generated by Django 2.1.4 on 2018-12-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0013_auto_20181213_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchtvseason',
            name='tmdb_season_id',
        ),
    ]
