# Generated by Django 2.1.4 on 2018-12-13 12:23

from django.db import migrations

from nefarious.tmdb import get_tmdb_client


def populate_seasons(apps, schema_editor):
    WatchTVSeason = apps.get_model('nefarious', 'WatchTVSeason')
    WatchTVEpisode = apps.get_model('nefarious', 'WatchTVEpisode')
    NefariousSettings = apps.get_model('nefarious', 'NefariousSettings')
    nefarious_settings = NefariousSettings.objects.get()

    tmdb_client = get_tmdb_client(nefarious_settings)

    for watch_episode in WatchTVEpisode.objects.all():
        episode_result = tmdb_client.TV_Episodes(watch_episode.watch_tv_show.tmdb_show_id, watch_episode.season_number, watch_episode.episode_number)
        episode = episode_result.info()

        season = WatchTVSeason.objects.filter(
            watch_tv_show=watch_episode.watch_tv_show,
            season_number=episode['season_number'],
        )
        if season.exists():
            season = season.get()
        else:
            season = WatchTVSeason(
                user=watch_episode.user,
                watch_tv_show=watch_episode.watch_tv_show,
                season_number=episode['season_number'],
            )
            season.save()
        watch_episode.watch_tv_season = season
        watch_episode.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0014_remove_watchtvseason_tmdb_season_id'),
    ]

    operations = [
        migrations.RunPython(populate_seasons),
    ]
