# Generated by Django 2.1.1 on 2018-12-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0014_remove_watchtvseason_tmdb_season_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchtvepisode',
            name='watch_tv_season',
        ),
    ]
