# Generated by Django 2.1.1 on 2018-12-14 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0015_remove_watchtvepisode_watch_tv_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchtvshow',
            name='quality_profile_custom',
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='collected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='transmission_torrent_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
