# Generated by Django 2.1.1 on 2018-12-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0016_auto_20181214_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmovie',
            name='last_attempt_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchtvepisode',
            name='last_attempt_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='last_attempt_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
