# Generated by Django 2.1.1 on 2019-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0019_jackettindexersettings_nefarious_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jackettindexersettings',
            name='nefarious_settings',
        ),
        migrations.AlterField(
            model_name='jackettindexersettings',
            name='ratio_management',
            field=models.CharField(choices=[('download & seed', 'download & seed'), ('seed', 'seed')], default='download & seed', max_length=100),
        ),
    ]
