# Generated by Django 2.1.1 on 2019-01-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0020_auto_20190107_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JackettIndexerSettings',
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='jackett_indexer_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
