# Generated by Django 2.1.1 on 2019-01-07 19:22

from django.db import migrations
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0020_auto_20190107_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JackettIndexerSettings',
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='jackett_indexer_settings',
            field=jsonfield.fields.JSONField(blank=True, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, null=True),
        ),
    ]
