# Generated by Django 2.1.1 on 2019-01-07 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0021_auto_20190107_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nefarioussettings',
            old_name='jackett_indexer_settings',
            new_name='jackett_indexers_seed',
        ),
    ]
