# Generated by Django 2.1.1 on 2019-01-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0022_auto_20190107_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='transmission_pass',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='transmission_user',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
