# Generated by Django 2.1.5 on 2019-03-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0023_auto_20190115_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='jackett_port',
            field=models.IntegerField(blank=True, default=9117),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='jackett_token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='transmission_host',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='transmission_port',
            field=models.IntegerField(blank=True, default=9091),
        ),
    ]
