# Generated by Django 2.1.5 on 2019-05-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0025_nefarioussettings_allow_hardcoded_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmovie',
            name='allow_hardcoded_subs_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchtvepisode',
            name='allow_hardcoded_subs_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='allow_hardcoded_subs_custom',
            field=models.BooleanField(default=False),
        ),
    ]
