# Generated by Django 2.1.5 on 2019-05-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0027_auto_20190527_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='transmission_pass',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='transmission_user',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
