# Generated by Django 2.1.5 on 2019-06-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0029_watchtvseasonrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchtvseasonrequest',
            unique_together={('watch_tv_show', 'season_number')},
        ),
    ]
