# Generated by Django 2.1.5 on 2019-06-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0030_auto_20190609_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchtvseasonrequest',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
