# Generated by Django 2.1.5 on 2019-07-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0031_watchtvseasonrequest_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='keyword_filters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
