# Generated by Django 2.1.5 on 2019-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0033_auto_20190730_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='keyword_filters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
