# Generated by Django 2.1.5 on 2019-08-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0037_auto_20190731_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmovie',
            name='renamed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchtvepisode',
            name='renamed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='renamed',
            field=models.BooleanField(default=False),
        ),
    ]
