# Generated by Django 2.1.5 on 2019-08-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0039_auto_20190812_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmovie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchtvshow',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
