# Generated by Django 2.1.5 on 2019-10-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0040_auto_20190816_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchtvseasonrequest',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
