# Generated by Django 2.1.5 on 2019-10-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0042_auto_20191019_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='jackett_token',
            field=models.CharField(default='COPY_YOUR_JACKETT_TOKEN_HERE', max_length=500),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='quality_profile_tv',
            field=models.CharField(choices=[('any', 'any'), ('sd', 'sd'), ('hd-720p', 'hd-720p'), ('hd-720p-1080p', 'hd-720p-1080p'), ('hd-1080p', 'hd-1080p'), ('ultra-hd', 'ultra-hd')], default='any', max_length=500),
        ),
    ]
