# Generated by Django 2.1.5 on 2019-10-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0043_auto_20191020_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='transmission_pass',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='transmission_user',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
