# Generated by Django 2.1.5 on 2019-10-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0044_auto_20191020_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nefarioussettings',
            name='jackett_indexers_seed',
        ),
    ]
