# Generated by Django 2.1.5 on 2019-10-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0046_remove_nefarioussettings_tmdb_configuration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
