# Generated by Django 2.1.5 on 2019-10-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0047_nefarioussettings_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='tmdb_languages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
