# Generated by Django 3.0.2 on 2020-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0048_nefarioussettings_tmdb_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchtvshow',
            name='auto_watch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchtvshow',
            name='auto_watch_date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
