# Generated by Django 3.0.2 on 2020-03-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0049_auto_20200329_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchtvshow',
            name='auto_watch_date_created',
        ),
        migrations.AddField(
            model_name='watchtvshow',
            name='auto_watch_date_requested',
            field=models.DateField(blank=True, null=True),
        ),
    ]
