# Generated by Django 3.0.2 on 2020-04-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0050_auto_20200329_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchtvshow',
            old_name='auto_watch_date_requested',
            new_name='auto_watch_date_updated',
        ),
    ]
