# Generated by Django 3.0.2 on 2020-04-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0051_auto_20200401_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='webhook_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='webhook_url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
