# Generated by Django 3.0.2 on 2020-04-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0052_auto_20200402_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='webhook_key',
            field=models.CharField(blank=True, default='text', max_length=50),
        ),
    ]
