# Generated by Django 3.0.2 on 2020-04-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0053_auto_20200402_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchtvepisode',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
