# Generated by Django 3.0.2 on 2020-06-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0057_auto_20200608_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmovie',
            name='download_path',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='watchtvepisode',
            name='download_path',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='watchtvseason',
            name='download_path',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
