# Generated by Django 3.0.2 on 2020-12-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0058_auto_20200608_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentblacklist',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
