# Generated by Django 3.0.2 on 2020-12-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0059_torrentblacklist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentblacklist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
