# Generated by Django 3.0.2 on 2021-03-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0060_auto_20201206_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='open_subtitles_api_key',
            field=models.CharField(default='LG7LMRIL9zfVmF537mxnQDEfN4V7LLqX', help_text='OpenSubtitles API Key', max_length=500),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='open_subtitles_password',
            field=models.CharField(blank=True, help_text='OpenSubtitles password', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='open_subtitles_user_token',
            field=models.CharField(blank=True, help_text='OpenSubtitles user auth token', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='open_subtitles_username',
            field=models.CharField(blank=True, help_text='OpenSubtitles username', max_length=500, null=True),
        ),
    ]
