# Generated by Django 3.0.2 on 2021-08-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0063_auto_20210610_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchtvshow',
            name='quality_profile_custom',
            field=models.CharField(blank=True, choices=[('any', 'any'), ('sd', 'sd'), ('hd-720p', 'hd-720p'), ('hd-720p-1080p', 'hd-720p-1080p'), ('hd-1080p', 'hd-1080p'), ('ultra-hd', 'ultra-hd')], max_length=500),
        ),
    ]
