# Generated by Django 3.0.2 on 2021-09-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0065_auto_20210829_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmovie',
            name='transmission_torrent_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='watchtvepisode',
            name='transmission_torrent_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='transmission_torrent_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
