# Generated by Django 3.0.2 on 2021-09-05 12:30
from django.db import migrations
from django.utils import timezone


def populate_last_attempt_date(apps, schema_editor):

    WatchMovie = apps.get_model('nefarious', 'WatchMovie')
    WatchTVEpisode = apps.get_model('nefarious', 'WatchTVEpisode')
    WatchTVSeason = apps.get_model('nefarious', 'WatchTVSeason')

    # populate missing last_attempt_date for everything already collected
    for model in [WatchMovie, WatchTVSeason, WatchTVEpisode]:
        for media in model.objects.filter(collected=True, last_attempt_date__isnull=True):
            media.last_attempt_date = timezone.utc.localize(timezone.datetime.utcnow())
            media.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0066_auto_20210904_2035'),
    ]

    operations = [
        migrations.RunPython(populate_last_attempt_date, reverse_code=lambda a, b: None),
    ]
