# Generated by Django 3.0.2 on 2021-10-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0067_populate_last_attempt_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nefarioussettings',
            name='webhook_key',
        ),
        migrations.RemoveField(
            model_name='nefarioussettings',
            name='webhook_url',
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='apprise_notification_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
