# Generated by Django 3.0.2 on 2021-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0068_auto_20211031_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmovie',
            name='quality_profile_custom',
            field=models.CharField(blank=True, choices=[('any', 'any'), ('sd', 'sd'), ('hd-720p', 'hd-720p'), ('hd-720p-1080p', 'hd-720p-1080p'), ('hd-1080p', 'hd-1080p'), ('ultra-hd', 'ultra-hd')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='watchtvseasonrequest',
            name='quality_profile_custom',
            field=models.CharField(blank=True, choices=[('any', 'any'), ('sd', 'sd'), ('hd-720p', 'hd-720p'), ('hd-720p-1080p', 'hd-720p-1080p'), ('hd-1080p', 'hd-1080p'), ('ultra-hd', 'ultra-hd')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='watchtvshow',
            name='quality_profile_custom',
            field=models.CharField(blank=True, choices=[('any', 'any'), ('sd', 'sd'), ('hd-720p', 'hd-720p'), ('hd-720p-1080p', 'hd-720p-1080p'), ('hd-1080p', 'hd-1080p'), ('ultra-hd', 'ultra-hd')], max_length=500, null=True),
        ),
    ]
