# Generated by Django 3.0.2 on 2022-07-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0069_auto_20211128_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='enable_fake_video_detection',
            field=models.BooleanField(default=False),
        ),
    ]
