# Generated by Django 3.0.2 on 2022-07-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0071_auto_20220704_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='enable_video_detection',
            field=models.BooleanField(default=False),
        ),
    ]
