# Generated by Django 3.0.2 on 2022-08-13 13:27

from django.db import migrations


def disable_video_detection(apps, schema_editor):
    NefariousSettings = apps.get_model('nefarious', 'NefariousSettings')

    nefarious_settings = NefariousSettings.objects.all().first()
    if not nefarious_settings:  # skip if no settings exist
        return
    nefarious_settings.enable_video_detection = False
    nefarious_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0072_auto_20220714_2111'),
    ]

    operations = [
        migrations.RunPython(disable_video_detection),
    ]
