# Generated by Django 3.0.2 on 2022-08-01 18:50

from django.db import migrations


def populate_quality_profile(apps, schema_editor):
    NefariousSettings = apps.get_model('nefarious', 'NefariousSettings')
    QualityProfile = apps.get_model('nefarious', 'QualityProfile')

    nefarious_settings = NefariousSettings.objects.get()
    QualityProfile.objects.create(
        name='TV',
        profile=nefarious_settings.quality_profile_tv,
    )
    QualityProfile.objects.create(
        name='Movie',
        profile=nefarious_settings.quality_profile_movies,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0073_auto_20220801_1850'),
    ]

    operations = [
        migrations.RunPython(populate_quality_profile, reverse_code=lambda a, b: None),
    ]
