# Generated by Django 3.0.2 on 2024-01-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0074_add_preferred_media_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='stuck_download_handling_days',
            field=models.IntegerField(default=3, help_text='How many days to wait before blacklisting stuck downloads'),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='stuck_download_handling_enabled',
            field=models.BooleanField(default=False, help_text='Whether to enable stuck download handling by blacklisting stuck torrents'),
        ),
    ]
