# Generated by Django 3.0.2 on 2022-08-01 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0074_quality_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualityprofile',
            old_name='profile',
            new_name='quality',
        ),
        migrations.AddField(
            model_name='qualityprofile',
            name='max_size_gb',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='qualityprofile',
            name='min_size_gb',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='qualityprofile',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
