# Generated by Django 3.0.2 on 2022-08-01 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0075_auto_20220801_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityprofile',
            name='max_size_gb',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='qualityprofile',
            name='min_size_gb',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
