# Generated by Django 3.0.2 on 2024-06-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0075_auto_20240114_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmovie',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watchtvepisode',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='watchtvseason',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
