# Generated by Django 3.0.2 on 2024-06-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0077_watchtvseasonrequest_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='jackett_filter_index',
            field=models.CharField(default='all', help_text='Optional Jackett index filter to use for searches', max_length=500),
        ),
    ]
