# Generated by Django 3.0.2 on 2024-07-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0078_nefarioussettings_jackett_filter_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='jackett_filter_index',
            field=models.CharField(blank=True, help_text='Optional Jackett index filter to use for searches', max_length=500, null=True),
        ),
    ]
