# Generated by Django 3.0.2 on 2024-07-26 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0078_nefarioussettings_jackett_filter_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('quality', models.CharField(choices=[('any', 'any'), ('sd', 'sd'), ('hd-720p', 'hd-720p'), ('hd-720p-1080p', 'hd-720p-1080p'), ('hd-1080p', 'hd-1080p'), ('ultra-hd', 'ultra-hd')], max_length=500)),
                ('min_size_gb', models.DecimalField(blank=True, decimal_places=2, help_text='minimum size to download', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_size_gb', models.DecimalField(blank=True, decimal_places=2, help_text='maximum size to download', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='quality_profiles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nefarious.QualityProfile'),
        ),
    ]
