# Generated by Django 3.0.2 on 2024-07-27 21:07

from django.db import migrations, transaction


def populate_quality_profile_media(apps, schema_editor):
    QualityProfile = apps.get_model('nefarious', 'QualityProfile')
    WatchMovie = apps.get_model('nefarious', 'WatchMovie')
    WatchTVShow = apps.get_model('nefarious', 'WatchTVShow')
    WatchTVSeasonRequest = apps.get_model('nefarious', 'WatchTVSeasonRequest')

    # copy default quality profile into new field
    for model in [WatchMovie, WatchTVShow, WatchTVSeasonRequest]:
        for media in model.objects.all():
            if media.quality_profile_custom:
                # find matching quality profile by the quality & type
                quality_profile = QualityProfile.objects.filter(
                    quality=media.quality_profile_custom,
                ).first()
                # assign quality profile
                media.quality_profile = quality_profile
                # must save in transaction
                with transaction.atomic():
                    media.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0080_populate_quality_profiles'),
    ]

    operations = [
        migrations.RunPython(populate_quality_profile_media, reverse_code=lambda a, b: None),
    ]
