# Generated by Django 3.0.2 on 2024-07-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0081_populate_quality_profile_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nefarioussettings',
            name='quality_profile_movies',
        ),
        migrations.RemoveField(
            model_name='nefarioussettings',
            name='quality_profile_tv',
        ),
    ]
