# Generated by Django 3.0.2 on 2024-07-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0082_auto_20240728_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nefarioussettings',
            old_name='quality_profile_movies_default',
            new_name='quality_profile_movies',
        ),
        migrations.RenameField(
            model_name='nefarioussettings',
            old_name='quality_profile_tv_default',
            new_name='quality_profile_tv',
        ),
    ]
