# Generated by Django 3.0.2 on 2024-07-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0083_auto_20240728_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchmovie',
            name='quality_profile_custom',
        ),
        migrations.RemoveField(
            model_name='watchtvseasonrequest',
            name='quality_profile_custom',
        ),
        migrations.RemoveField(
            model_name='watchtvshow',
            name='quality_profile_custom',
        ),
    ]
