# Generated by Django 3.0.2 on 2024-08-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0085_auto_20240801_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityprofile',
            name='is_hdr',
            field=models.BooleanField(default=False),
        ),
    ]
