# Generated by Django 3.0.2 on 2024-08-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0086_qualityprofile_is_hdr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityprofile',
            name='is_hdr',
        ),
        migrations.AddField(
            model_name='qualityprofile',
            name='hdr',
            field=models.BooleanField(default=False, help_text='media must be in HDR (High Dynamic Range)'),
        ),
    ]
