# Generated by Django 3.0.2 on 2024-08-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0087_auto_20240802_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualityprofile',
            old_name='hdr',
            new_name='require_hdr',
        ),
    ]
