# Generated by Django 3.0.2 on 2024-08-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0088_auto_20240802_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityprofile',
            name='require_five_point_one',
            field=models.BooleanField(default=False, help_text='media must be in 5.1 surround sound (e.g. Dolby 5.1)'),
        ),
    ]
