# Generated by Django 3.0.2 on 2024-08-16 12:48

from django.conf import settings
from django.db import migrations, models
import nefarious.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nefarious', '0092_auto_20240816_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchmovie',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(nefarious.models.get_first_admin_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchtvepisode',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(nefarious.models.get_first_admin_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchtvseason',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(nefarious.models.get_first_admin_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchtvseasonrequest',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(nefarious.models.get_first_admin_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchtvshow',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(nefarious.models.get_first_admin_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
