# Generated by Django 3.0.2 on 2024-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0096_auto_20240816_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityprofile',
            name='require_five_point_one',
            field=models.BooleanField(default=False, help_text='media must be in 5.1 surround sound (e.g. Dolby 5.1)', null=True),
        ),
        migrations.AlterField(
            model_name='qualityprofile',
            name='require_hdr',
            field=models.BooleanField(default=False, help_text='media must be in HDR (High Dynamic Range)', null=True),
        ),
    ]
