# Generated by Django 3.0.2 on 2025-08-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0097_auto_20240816_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchtvepisode',
            name='tmdb_episode_id',
            field=models.IntegerField(),
        ),
    ]
