# Generated by Django 3.0.2 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0098_auto_20250826_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='remove_completed_torrents_from_transmission',
            field=models.BooleanField(
                default=False,
                help_text='Remove torrents from Transmission after successful import without deleting imported files',
            ),
        ),
    ]
