# Generated by Django 4.2.30 on 2026-06-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0098_auto_20250826_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nefarioussettings',
            name='keyword_search_filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='tmdb_configuration',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='nefarioussettings',
            name='tmdb_languages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
