# Generated by Django 3.0.2 on 2025-12-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0098_auto_20250826_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='API token for OpenAI compatible provider', max_length=1000),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='ai_base_url',
            field=models.CharField(blank=True, default='https://api.openai.com/v1', help_text='OpenAI compatible base url', max_length=1000),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='ai_model',
            field=models.CharField(blank=True, default='gpt-4o-mini', help_text='Model to use for AI queries', max_length=100),
        ),
    ]
