# Generated by Django 3.0.2 on 2026-09-15

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0099_nefarioussettings_remove_completed_torrents_from_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='jackett_admin_password',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Optional Jackett admin password used to sync indexer tags',
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='jackett_search_timeout',
            field=models.IntegerField(
                default=90,
                help_text='Maximum seconds to wait for each Jackett request',
                validators=[MinValueValidator(1), MaxValueValidator(120)],
            ),
        ),
        migrations.AddField(
            model_name='nefarioussettings',
            name='jackett_serialize_flaresolverr_indexers',
            field=models.BooleanField(
                default=False,
                help_text='Search FlareSolverr-tagged and repeatedly slow Jackett indexers serially',
            ),
        ),
        migrations.CreateModel(
            name='JackettIndexer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexer_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('is_flaresolverr', models.BooleanField(default=None, null=True)),
                ('is_flaresolverr_manual_override', models.BooleanField(blank=True, default=None, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name', 'indexer_id'),
            },
        ),
    ]
