# Generated by Django 3.0.2 on 2026-09-15

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nefarious', '0099_nefarioussettings_remove_completed_torrents_from_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='nefarioussettings',
            name='jackett_search_timeout',
            field=models.IntegerField(
                default=90,
                help_text='Maximum seconds to wait for each Jackett request',
                validators=[MinValueValidator(1), MaxValueValidator(120)],
            ),
        ),
    ]
